### ISSUE TITLE
:result value error

### ISSUE THREAD

**Issue by fkgruber** [frederic-santos/ob-julia#1] opened 2020-10-12 19:25 UTC
Hi Frederic,

I know you are still working on this but I gave it a try anyways. The :results output works well with ess-julia  but could not get it to work with :results value. I get the error:

```
ERROR: LoadError: UndefVarError: @pipe not defined
in expression starting at none:1
```

**Comment by frederic-santos** [comment] 2020-10-12 19:52
Thanks for the report!

It looks like the Julia init file is not loaded at the start of your Julia session. I've tested on another (Linux) computer from a blank install and everything is fine for me.

1. Can you confirm that you've downloaded the whole repo, including `ob-ess-julia-startup.jl`?
2. Are you on Windows (or Mac)? In this case, this might have something to do with [this part of the code](https://github.com/frederic-santos/ob-ess-julia/blob/9dd7d43bdaf2974a41e3ddf71f5b3d2ef32384c3/ob-ess-julia.el#L105). Maybe the dir path is not correctly expanded for Windows users... I'll give it a try on Windows soon.

**Comment by fkgruber** [comment] 2020-10-13 01:45
I'm on windows.

I only downloaded one file. I tried downloading the whole directory now and using the following in my configuration:
```
(add-to-list 'load-path "~/elisp/ob-ess-julia/ob-ess-julia-master")
(require 'ob-ess-julia)
(setq org-src-lang-modes
      (append org-src-lang-modes '(("ess-julia" . ess-julia))))

;; Shortcuts for Julia code block headers.
;; Shortcut for "normal" session evaluation with verbatim outpuevalt:
(add-to-list 'org-structure-template-alist
	     '("j" . "src ess-julia :results output :session *julia* :exports both"))
;; Shortcut for inline graphical output within a session:
(add-to-list 'org-structure-template-alist
	     '("jfig" . "src ess-julia :results output graphics file :file FILENAME.png :session *julia* :exports both"))
;; Shortcut for well-formatted org table output within a session:
(add-to-list 'org-structure-template-alist
	     '("jtab" . "src ess-julia :results value table :session *julia* :exports both :colnames yes"))

```
But It is still not reading the init file.

 I then tried copying the content of your init file to
~/.julia/config/startup.jl and now it works!

This if my startup.jl:

```
# Check that required packages are installed:
if Base.find_package("CSV") == nothing || Base.find_package("DelimitedFiles") == nothing || Base.find_package("Pipe") == nothing
    using Pkg
    Pkg.add("CSV")
    Pkg.add("DelimitedFiles")
    Pkg.add("Pipe")
end

# Load required packages:
using CSV
using DelimitedFiles
using Pipe

# Perso function to write Julia objects into CSV files:
function ob_ess_julia_csv_write(filename, bodycode, has_header)
    CSV.write(filename, bodycode, delim = "\t", writeheader = has_header);
end

function ob_ess_julia_write(bodycode::Any, filename::Any, has_header::Any)
    try
        ob_ess_julia_csv_write(filename, bodycode, has_header);
    catch err
        if isa(err, ArgumentError) | isa(err, MethodError)
            writedlm(filename, bodycode)
        end
    end
end


println("In startup script")
using Base: stdin, stdout, stderr
using REPL.Terminals: TTYTerminal
using REPL: BasicREPL, run_repl
using DelimitedFiles
run_repl(BasicREPL(TTYTerminal("emacs",stdin,stdout,stderr)))
println("Finished initial startup")

```

The last lines are needed in windows otherwise the shell does not show anything
 
> Thanks for the report!
> 
> It looks like the Julia init file is not loaded at the start of your Julia session. I've tested on another (Linux) computer from a blank install and everything is fine for me.
> 
> 1. Can you confirm that you've downloaded the whole repo, including `ob-ess-julia-startup.jl`?
> 2. Are you on Windows (or Mac)? In this case, this might have something to do with [this part of the code](https://github.com/frederic-santos/ob-ess-julia/blob/9dd7d43bdaf2974a41e3ddf71f5b3d2ef32384c3/ob-ess-julia.el#L105). Maybe the dir path is not correctly expanded for Windows users... I'll give it a try on Windows soon.

**Comment by frederic-santos** [comment] 2020-10-14 08:57
Thank you for investigating and for those useful comments.

> The last lines are needed in windows otherwise the shell does not show anything

I had no idea of that, but this is fixed in commit 1ce85d7d791e4d7cb. Thanks. However,

> But It is still not reading the init file.

I could not reproduce this problem. I tried on a Windows 10 computer: the init file was correctly detected and there was no problem for me.
Just in case, I updated config info in commit 5edd1140e163adcb1.

**Comment by fkgruber** [comment] 2020-10-14 15:58
thanks!

**Comment by fkgruber** [comment] 2020-10-20 17:46
Hi Frederic, 
I was trying on a Mac and I'm running into the same issue that it is not loading the startup.

THis is what I'm using on my init:
```
;; Load ob-julia and dependencies
(use-package julia-mode
  :ensure t)
(add-to-list 'load-path "~/elisp/ob-ess-julia/")
(require 'ob-ess-julia)
;; Add ess-julia into supported languages:
(org-babel-do-load-languages 'org-babel-load-languages
                             (append org-babel-load-languages
                                     '((ess-julia . t))))
;; Link this language to ess-julia-mode (although it should be done by default):
(setq org-src-lang-modes
      (append org-src-lang-modes '(("ess-julia" . ess-julia))))

```

I have a clone of your repository in ob-ess-julia.
Am I missing some configuration? or do I need to move the startup file somewhere? How does it know to load up the startup file from this location?

thanks
FKG

**Comment by frederic-santos** [comment] 2020-10-21 08:09
Hi again,
Had you still the same issue on Windows, or could it be fixed with this new elisp config?

I have unfortunately no way to test that on a Mac. However, since I could not reproduce that issue on Windows, I'm a bit confused.
In my code:
1. [Here](https://github.com/frederic-santos/ob-ess-julia/blob/b3abe106ac2d6106d61678bfbe4316fc5d5627bf/ob-ess-julia.el#L63), the path to `ob-ess-julia-startup.jl` is built. It's simply defined as being the same folder in which `ob-ess-julia.el` can be found.
2. And then Julia is started with the additional instruction of [loading this Julia startup file](https://github.com/frederic-santos/ob-ess-julia/blob/b3abe106ac2d6106d61678bfbe4316fc5d5627bf/ob-ess-julia.el#L106).

There may be some OS-specific subtlety I'm not aware of...
When you start Emacs and do `C-h v ob-ess-julia-startup`, what is the value of this variable?

**Comment by fkgruber** [comment] 2020-10-21 13:52
Hi Frederic,
I see what the problem is now. I have been starting julia with M-x julia. That won't load that startup file.

However, if I try to run a block in orgmode  pointing to a new *session* then it tries to run `run-ess-julia` which does not exists:
`set-buffer: Symbol’s function definition is void: run-ess-julia`

What is run-ess-julia defined?

thanks
FKG

**Comment by frederic-santos** [comment] 2020-10-21 16:19
> I have been starting julia with M-x julia. That won't load that startup file.

Oh, yes! Actually, Julia sessions should be started automatically with a `C-c C-c` on a code block. It won't work if the Julia process is started manually, indeed. That's something I should have said in the documentation, you're right.

> it tries to run `run-ess-julia` which does not exists

This is strange: this function [is defined in ESS](https://github.com/emacs-ess/ESS/blob/a694b2627992bda5489c1b4b5bb750c590aa8d85/lisp/ess-julia.el#L412). It should have been recognized. I added another `declare-function` statement, just in case, in commit 9dd19047bd14387d0a695b2ef9625932de7c4b56.

**Comment by fkgruber** [comment] 2020-10-21 20:38
I'm using ess-version: 18.10.2.  I wonder if julia-mode is overwriting some of the julia related code  in ess.

**Comment by fkgruber** [comment] 2020-10-21 20:50
this version does not defined that function:
https://github.com/emacs-ess/ESS/blob/ess-18.10/lisp/ess-julia.el

run-ess-julia is only defined on the development version 
18.10.3snapshot
https://github.com/emacs-ess/ESS/blob/master/lisp/ess-julia.el

**Comment by fkgruber** [comment] 2020-10-21 21:43
I updated to the development version of ess and now everything works.

thanks
Fred

**Comment by frederic-santos** [comment] 2020-10-22 05:52
Thanks, good to know that everything is okay now!

**Closed as completed by frederic-santos** 2020-10-22 05:52 UTC
Labels: windows
